default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: veggie_app_development

test:
  <<: *default
  database: veggie_app_test

production:
  <<: *default
  database: veggie_app_production
