# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3d415bc61f6875dcfd053352cb7640fd9a977e19228ee03fbca2a8a511766715b1842f48f19889d54d332cb75495e5a1f271bcf619395c285fc565a08283cea

test:
  secret_key_base: 1cb34dd5393741266e327553d5c5e9713d8f3d4fb1ae0e662976a463f2ace975e85eeb8e098e91bacd8959fdc3c7464ce2c3fe48ab8b478bb88bf95a88542023

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
